name: Create Repositories

on:
  push:
    branches:
      - main

jobs:
  create-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Files
        run: ls repos_to_create/*.json

      - name: Process Files and Create Repos
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          for file in repos_to_create/*.json; do
            repo_name=$(jq -r '.repository' "$file")
            echo $repo_name            
            # Verifica si el repositorio ya existe
            repo_check=$(curl -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/felipe0410/"$repo_name")

            if [ "$repo_check" == "200" ]; then
              echo "El repositorio $repo_name ya existe. No se realizará ninguna acción."
            else
              curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/orgs/go-pos/repos \
              -d '{"name":"'"$repo_name"'","description":"This is your first repository","homepage":"https://github.com","private":true,"has_issues":true,"has_projects":true,"has_wiki":true}'
              # ___________________________-


              # Crea el repositorio
              # ...
              # Clona el repositorio recién creado
              # git clone https://github.com/usuario/"$repo_name".git

              # # Copia la estructura base al repositorio local
              # cp -R ruta-a-la-estructura-base/* "$repo_name"/

              # # Agrega los cambios y realiza el commit
              # cd "$repo_name"
              # git add .
              # git commit -m "Añadir estructura base"
              # git push origin main

              echo "Repositorio $repo_name creado con éxito y estructura base añadida."
            fi
          done
